### ISSUE TITLE
Build it?

### ISSUE THREAD

**Issue by pepa65** [gphalkes/tilde#14]
I can't figure out how to build tilde. I guess there is also dependencies on some of your other github repo. Any pointers?

**Comment by gphalkes** [comment]
I would advise only building from the github repositories if you wish to develop on Tilde. Otherwise, it is easier to either install the binary packages provided via https://os.ghalkes.nl/tilde, or build from the official releases from that address. That said, if you wish to build from the github repository, here are the instructions.

Building tilde requires the following repos:
gphalkes/makesys
gphalkes/transcript
gphalkes/t3shared
gphalkes/t3config
gphalkes/t3key
gphalkes/t3highlight
gphalkes/t3window
gphalkes/t3widget
gphalkes/tilde

once these are cloned, such that each of them is a subdirectory of the same directory, then from that directory a simple

t3shared/doall make -C src

should build tilde (provided all the relevant dependencies are installed.

**Comment by pepa65** [comment]
Thanks, great information. Maybe even worth documenting somewhere else accessible as well, also in the spirit of GPL.

**Comment by pepa65** [comment]
Rereading the current instruction (about other dependencies and installing LLnextgen) it does all seem to be complete now. Can get to the debug build.

**Comment by pepa65** [comment]
I have just done this:
```
for i in makesys transcript t3shared t3window t3widget t3key t3config t3highlight
do
  (cd "$i"; git pull)
done

t3shared/doall make -C src
```
In building `tilde`, the message comes: `find: ‘.recordings/’: No such file or directory`, and when running the resulting `edit` binary, the output is:
```
Debug mode: Setting VM limit
Error: libtranscript: Bad file descriptor
init failed
```
`

**Comment by gphalkes** [comment]
The messages about find: ‘.recordings/’: No such file or directory are harmless. They are related to storing recordings of sessions if you use termdebug and the tedit script.

The libtranscript error very likely means that libtranscript could not find the converters that were built (they are in some hidden directory immediately after the build). Did you do anything in between the "t3shared/doall make -C src" and "tilde/src/.objects/edit" commands?
