### ISSUE TITLE
The lines are lined up "ladder" (with screenshot)

### ISSUE THREAD

**Issue by xintrea** [gphalkes/tilde#17]
I am select several lines, press Ctrl+C. Move cursor at one line down and press Ctrl+V.

And all lines insert with additional spaces. At each next line the count of spases is increment to 2. 

Screen shot:
http://i.piccy.info/i9/241c2db835aaef4fae6b40abf2a1ba95/1513431834/130640/1202516/scr0030.png

**Comment by gphalkes** [comment]
This is typically what happens if pasting is done by the terminal emulator rather than by Tilde itself. Is it possible that ctrl-v is bound to paste in the terminal emulator?

**Comment by xintrea** [comment]
Yes, this bug if put text from DE buffer.

A similar bug was in the Midnight Commander. But they were able to fix it, something they wrote down to correct the behavior of the terminal.

**Comment by gphalkes** [comment]
I think you are referring to https://midnight-commander.org/ticket/1603. What is going on there is that mcedit works around this issue for the specific case of middle-click-paste, which is possible because of the following reasons:
* To trigger the "ladder" behavior, the user needs to use shift-middle-mouse-button
* mcedit queries X11 directly (not the terminal!) to get the state of the modifiers (the shift key for this case)
*  shift-enter is interpreted as "newline without auto-indent" in mcedit in general, not just for this specific case

Note that this does not work for anything other than middle-click-paste. Further, the mcedit trick of querying X11 for the modifier state is something I do not wish to reproduce. It is fragile, as it requires that the querying of X11 is done very quickly after the button is actually pressed, which is something which can not be guaranteed when using Tilde over SSH (with X11 forwarding enabled). It would also add more cases where the behavior of Tilde changes due to the environment, which is something I wish to limit as much as possible, as it is surprising to users.

As indicated, it looks like your terminal emulator is set up to interpret ctrl-c as paste, rather than passing it to the program running on the terminal. You either have to configure your terminal emulator not to do that, or try pressing ctrl-shift-c instead.

**Comment by gphalkes** [comment]
Added a feature request bug (#19) which might be useful for some cases.

**Comment by gphalkes** [comment]
I actually stumbled across the solution for this problem (called bracketed paste), and implemented a fix in https://github.com/gphalkes/t3widget/commit/4d7bf7ee9b2a3310855c6897714aba552b47d6ac, which will be part of the next release of libt3widget.

**Comment by gphalkes** [comment]
This is fixed by libt3widget release 0.6.0
