### ISSUE TITLE
Expired GPG key?

### ISSUE THREAD

**Issue by nraygun** [gphalkes/tilde#46]
I think the GPG key in OBS repositories expired:
```
pub   rsa2048 2017-04-16 [SC] [expired: 2019-06-25]
      78F9 1C8F 27BC 3952 84BC  9C61 20BE ECE5 E0B2 0CEA
uid           [ expired] home:gphalkes OBS Project <home:gphalkes@build.opensuse.org>

```
Can you renew it please?

**Comment by gphalkes** [comment]
Sorry for the delay, I've been on holiday. The repository should work again now. Thanks for reporting it.

**Comment by nraygun** [comment]
Thanks, but I still seem to get an error message. Any ideas?

W: GPG error:
http://download.opensuse.org/repositories/home:/gphalkes:/tilde/xUbuntu_18.04
./ Release: The following signatures were invalid: EXPKEYSIG
20BEECE5E0B20CEA home:gphalkes OBS Project <home:gphalkes@build.opensuse.org
>
E: The repository '
http://download.opensuse.org/repositories/home:/gphalkes:/tilde/xUbuntu_18.04
./ Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore
disabled by default.

**Comment by gphalkes** [comment]
This is a bit unfortunate, but it is caused by the fact that updating the key on the repository side doesn't propagate to the clients. What I should have done is refresh the key and the tilde-keyring package before the key expired, allowing clients to update the key before it expires (I think).

Anyway, the way to get things working again is to either do (not really recommended):

apt-get --allow-unauthenticated update ; apt-get --allow-unauthenticated upgrade

Or manually download the new tilde-keyring package from https://download.opensuse.org/repositories/home:/gphalkes:/tilde/xUbuntu_19.04/all/tilde-keyring_2019.07.18-1_all.deb and use

dpkg -i tilde-keyring_2019.07.18-1_all.deb

on the downloaded package.

After that everything should work again.

**Comment by nraygun** [comment]
That did the trick! Thanks again!

-Manny
